"""Added More Tables

Revision ID: 1a9b97f109fc
Revises: 55eb857731a7
Create Date: 2020-05-11 13:37:37.599615

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1a9b97f109fc'
down_revision = '55eb857731a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_user_id', sa.Integer(), nullable=True),
    sa.Column('received_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_user_id', sa.Integer(), nullable=True),
    sa.Column('from_store_id', sa.Integer(), nullable=False),
    sa.Column('to_store_id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['received_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sent_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hold_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('identity', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('in_store', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_items')
    op.drop_table('hold_item')
    op.drop_table('store_transfer')
    # ### end Alembic commands ###
