"""Added Other Stock Id

Revision ID: 263d0a8055e8
Revises: 710cba898ad3
Create Date: 2020-05-11 16:07:29.277329

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '263d0a8055e8'
down_revision = '710cba898ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_item', sa.Column('other_stock_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_item', 'stock', ['other_stock_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_item', type_='foreignkey')
    op.drop_column('transfer_item', 'other_stock_id')
    # ### end Alembic commands ###
