"""Added Foreign keys

Revision ID: 4997304d0b15
Revises: 1a9b97f109fc
Create Date: 2020-05-11 13:38:03.341540

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4997304d0b15'
down_revision = '1a9b97f109fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_items', sa.Column('store_transfer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transfer_items', 'store_transfer', ['store_transfer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_items', type_='foreignkey')
    op.drop_column('transfer_items', 'store_transfer_id')
    # ### end Alembic commands ###
