"""Added Amount To HoldItem

Revision ID: 4e46022a40ec
Revises: 263d0a8055e8
Create Date: 2020-05-19 13:53:55.758852

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4e46022a40ec'
down_revision = '263d0a8055e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hold_item', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hold_item', 'amount')
    # ### end Alembic commands ###
