"""Some More Stock Tables

Revision ID: 9bc0b39fe891
Revises: de9cbd217e6e
Create Date: 2020-05-05 13:38:30.336131

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bc0b39fe891'
down_revision = 'de9cbd217e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('transactions', sa.Integer(), nullable=True),
    sa.Column('taken', sa.Float(), nullable=False),
    sa.Column('add', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('catalog_report')
    op.add_column('request', sa.Column('store_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'request', 'store', ['store_id'], ['id'])
    op.add_column('transaction', sa.Column('stock_id', sa.Integer(), nullable=False))
    op.drop_constraint('transaction_ibfk_1', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'stock', ['stock_id'], ['id'])
    op.drop_column('transaction', 'catalog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('catalog_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_ibfk_1', 'transaction', 'catalog', ['catalog_id'], ['id'])
    op.drop_column('transaction', 'stock_id')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'store_id')
    op.create_table('catalog_report',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('catalog_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('taken', mysql.FLOAT(), nullable=False),
    sa.Column('add', mysql.FLOAT(), nullable=False),
    sa.Column('remaining', mysql.FLOAT(), nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.Column('transactions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], name='catalog_report_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('stock_report')
    # ### end Alembic commands ###
